// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dehpujfojocejfstmgbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlaHB1amZvam9jZWpmc3RtZ2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODM1ODUsImV4cCI6MjA2NDE1OTU4NX0.fN98T-yOyyK2izZF8ZOgoErw76yNkcVXBuUK2fueSJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);